name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Test:
    if: |
      github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nim-version: ['2.2.8']

    name: ${{ matrix.os }}-nim-${{ matrix.nim-version }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}

    - name: Test
      shell: bash
      run: |
        nim --version
        NIM_BIN="$(command -v nim)"
        nimble --nim:"${NIM_BIN}" install -dy
        nimble --nim:"${NIM_BIN}" test
